name: DSNode
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      # Install dependencies
      - run: npm install

      # build
      - run: npm run build

      # Run tests
      - run: npm run test