name: DSNode

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: npm

      # Install npm dependencies
      - name: Install dependencies
        run: npm install

      # build
      - name: Build project
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm run test

      # Format
      - name: Run formating test
        run: npm run format:test